//2-Inserción colección 
db.Cursos.insertMany([
  {
    _id: "C001",
    titulo: "Introducción a MongoDB para Desarrolladores",
    descripcion: "Aprende los fundamentos de MongoDB, desde la instalación hasta operaciones CRUD y modelado de datos.",
    instructor: "I0001",
    categoria: "Bases de Datos",
    tags: ["MongoDB", "NoSQL", "Bases de Datos", "Desarrollo Backend"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-05-01T10:00:00-06:00"),
    fechaActualizacion: ISODate("2025-05-20T14:30:00-06:00"),
    precio: 29.99,
    imagenPortada: "https://ejemplo.com/imagenes/mongodb_curso.jpg",
    duracionEstimada: "4 horas",
    lecciones: ["L001", "L002", "L003", "L004", "L005"],
    evaluaciones: ["E001"],
    recursosAdicionales: [
      {
        nombre: "Guía de instalación MongoDB",
        tipo: "PDF",
        url: "https://ejemplo.com/recursos/mongodb_instalacion.pdf",
      },
    ],
    estudiantesInscritos: 75,
    calificacionPromedio: 4.5,
  },
  {
    _id: "C002",
    titulo: "JavaScript Moderno: De Cero a Experto",
    descripcion: "Domina JavaScript con las últimas características de ES6+, asincronismo y manipulación del DOM.",
    instructor: "I0002",
    categoria: "Programación",
    tags: ["JavaScript", "Frontend", "Web Development", "ES6"],
    nivel: "Intermedio",
    idioma: "es",
    fechaCreacion: ISODate("2025-04-15T09:30:00-06:00"),
    fechaActualizacion: ISODate("2025-05-25T11:00:00-06:00"),
    precio: 39.99,
    imagenPortada: "https://ejemplo.com/imagenes/javascript_curso.jpg",
    duracionEstimada: "8 horas",
    lecciones: ["L006", "L007", "L008", "L009", "L010", "L011"],
    evaluaciones: ["E002"],
    recursosAdicionales: [
      {
        nombre: "Ejercicios de JavaScript",
        tipo: "ZIP",
        url: "https://ejemplo.com/recursos/js_ejercicios.zip",
      },
    ],
    estudiantesInscritos: 120,
    calificacionPromedio: 4.7,
  },
  {
    _id: "C003",
    titulo: "Diseño Gráfico con Adobe Photoshop",
    descripcion: "Aprende a usar Adobe Photoshop para crear diseños impresionantes, desde retoque fotográfico hasta diseño de logos.",
    instructor: "I0002",
    categoria: "Diseño",
    tags: ["Photoshop", "Diseño Gráfico", "Edición de Imagen", "Creatividad"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-03-20T11:00:00-06:00"),
    fechaActualizacion: ISODate("2025-05-10T16:00:00-06:00"),
    precio: 45.00,
    imagenPortada: "https://ejemplo.com/imagenes/photoshop_curso.jpg",
    duracionEstimada: "6 horas",
    lecciones: ["L012", "L013", "L014", "L015"],
    evaluaciones: ["E003"],
    recursosAdicionales: [
      {
        nombre: "Archivos de práctica Photoshop",
        tipo: "ZIP",
        url: "https://ejemplo.com/recursos/ps_practica.zip",
      },
    ],
    estudiantesInscritos: 90,
    calificacionPromedio: 4.6,
  },
  {
    _id: "C004",
    titulo: "Desarrollo Web con React y Redux",
    descripcion: "Crea aplicaciones web modernas y escalables usando React y Redux, la combinación perfecta para el frontend.",
    instructor: "I0001",
    categoria: "Programación",
    tags: ["React", "Redux", "Frontend", "JavaScript", "Web Development"],
    nivel: "Avanzado",
    idioma: "es",
    fechaCreacion: ISODate("2025-02-10T14:00:00-06:00"),
    fechaActualizacion: ISODate("2025-06-01T10:00:00-06:00"),
    precio: 59.99,
    imagenPortada: "https://ejemplo.com/imagenes/react_redux_curso.jpg",
    duracionEstimada: "10 horas",
    lecciones: ["L016", "L017", "L018", "L019", "L020", "L021", "L022"],
    evaluaciones: ["E004"],
    recursosAdicionales: [
      {
        nombre: "Repositorio GitHub del proyecto",
        tipo: "URL",
        url: "https://github.com/ejemplo/react-redux-curso",
      },
    ],
    estudiantesInscritos: 150,
    calificacionPromedio: 4.8,
  },
  {
    _id: "C005",
    titulo: "Fundamentos de Python para Ciencia de Datos",
    descripcion: "Iníciate en Python y sus librerías esenciales (NumPy, Pandas, Matplotlib) para el análisis de datos.",
    instructor: "I0004",
    categoria: "Ciencia de Datos",
    tags: ["Python", "Data Science", "Análisis de Datos", "Programación"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-01-25T13:00:00-06:00"),
    fechaActualizacion: ISODate("2025-05-15T10:00:00-06:00"),
    precio: 34.99,
    imagenPortada: "https://ejemplo.com/imagenes/python_datascience_curso.jpg",
    duracionEstimada: "7 horas",
    lecciones: ["L023", "L024", "L025", "L026", "L027"],
    evaluaciones: ["E005"],
    recursosAdicionales: [
      {
        nombre: "Notebooks de Jupyter",
        tipo: "ZIP",
        url: "https://ejemplo.com/recursos/python_notebooks.zip",
      },
    ],
    estudiantesInscritos: 100,
    calificacionPromedio: 4.6,
  },
  {
    _id: "C006",
    titulo: "Marketing Digital: Estrategias de Contenido",
    descripcion: "Aprende a crear y ejecutar estrategias de contenido efectivas para impulsar tu marca en el entorno digital.",
    instructor: "I0003",
    categoria: "Marketing",
    tags: ["Marketing Digital", "Contenido", "SEO", "Redes Sociales"],
    nivel: "Intermedio",
    idioma: "es",
    fechaCreacion: ISODate("2025-04-01T10:30:00-06:00"),
    fechaActualizacion: ISODate("2025-05-28T15:00:00-06:00"),
    precio: 49.00,
    imagenPortada: "https://ejemplo.com/imagenes/marketing_digital_curso.jpg",
    duracionEstimada: "5 horas",
    lecciones: ["L028", "L029", "L030", "L031"],
    evaluaciones: ["E006"],
    recursosAdicionales: [
      {
        nombre: "Plantillas de calendario editorial",
        tipo: "XLSX",
        url: "https://ejemplo.com/recursos/calendario_editorial.xlsx",
      },
    ],
    estudiantesInscritos: 60,
    calificacionPromedio: 4.4,
  },
  {
    _id: "C007",
    titulo: "Ciberseguridad para Principiantes",
    descripcion: "Conoce los principios básicos de la ciberseguridad y protege tus sistemas y datos de amenazas comunes.",
    instructor: "I0005",
    categoria: "Ciberseguridad",
    tags: ["Seguridad Informática", "Ciberseguridad", "Redes", "Protección de Datos"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-03-05T09:00:00-06:00"),
    fechaActualizacion: ISODate("2025-05-01T12:00:00-06:00"),
    precio: 35.00,
    imagenPortada: "https://ejemplo.com/imagenes/ciberseguridad_curso.jpg",
    duracionEstimada: "6 horas",
    lecciones: ["L032", "L033", "L034", "L035", "L036"],
    evaluaciones: ["E007"],
    recursosAdicionales: [
      {
        nombre: "Lista de verificación de seguridad",
        tipo: "PDF",
        url: "https://ejemplo.com/recursos/checklist_seguridad.pdf",
      },
    ],
    estudiantesInscritos: 85,
    calificacionPromedio: 4.3,
  },
  {
    _id: "C008",
    titulo: "Blockchain y Criptomonedas: Introducción",
    descripcion: "Entiende qué es Blockchain, cómo funcionan las criptomonedas y sus aplicaciones más allá de Bitcoin.",
    instructor: "I0004",
    categoria: "Tecnología",
    tags: ["Blockchain", "Criptomonedas", "Fintech", "Innovación"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-02-20T11:00:00-06:00"),
    fechaActualizacion: ISODate("2025-06-05T09:00:00-06:00"),
    precio: 25.00,
    imagenPortada: "https://ejemplo.com/imagenes/blockchain_curso.jpg",
    duracionEstimada: "3 horas",
    lecciones: ["L037", "L038", "L039"],
    evaluaciones: ["E008"],
    recursosAdicionales: [
      {
        nombre: "Glosario de términos Blockchain",
        tipo: "PDF",
        url: "https://ejemplo.com/recursos/blockchain_glosario.pdf",
      },
    ],
    estudiantesInscritos: 70,
    calificacionPromedio: 4.2,
  },
  {
    _id: "C009",
    titulo: "Desarrollo de Apps Móviles con Flutter",
    descripcion: "Crea aplicaciones móviles nativas para iOS y Android con una sola base de código usando Flutter y Dart.",
    instructor: "I0003",
    categoria: "Desarrollo Móvil",
    tags: ["Flutter", "Dart", "Desarrollo Móvil", "Multiplataforma"],
    nivel: "Intermedio",
    idioma: "es",
    fechaCreacion: ISODate("2025-01-10T10:00:00-06:00"),
    fechaActualizacion: ISODate("2025-05-30T14:00:00-06:00"),
    precio: 65.00,
    imagenPortada: "https://ejemplo.com/imagenes/flutter_curso.jpg",
    duracionEstimada: "12 horas",
    lecciones: ["L040", "L041", "L042", "L043", "L044", "L045", "L046"],
    evaluaciones: ["E009"],
    recursosAdicionales: [
      {
        nombre: "Código fuente del proyecto de ejemplo",
        tipo: "ZIP",
        url: "https://ejemplo.com/recursos/flutter_proyecto.zip",
      },
    ],
    estudiantesInscritos: 110,
    calificacionPromedio: 4.7,
  },
  {
    _id: "C010",
    titulo: "Introducción a la Inteligencia Artificial",
    descripcion: "Explora los conceptos fundamentales de la IA, el aprendizaje automático y sus aplicaciones prácticas.",
    instructor: "I0001",
    categoria: "Inteligencia Artificial",
    tags: ["IA", "Machine Learning", "Deep Learning", "Tecnología"],
    nivel: "Básico",
    idioma: "es",
    fechaCreacion: ISODate("2025-03-15T10:00:00-06:00"),
    fechaActualizacion: ISODate("2025-06-08T11:00:00-06:00"),
    precio: 49.99,
    imagenPortada: "https://ejemplo.com/imagenes/ia_curso.jpg",
    duracionEstimada: "8 horas",
    lecciones: ["L047", "L048", "L049", "L050", "L051"],
    evaluaciones: ["E010"],
    recursosAdicionales: [
      {
        nombre: "Lecturas recomendadas sobre IA",
        tipo: "PDF",
        url: "https://ejemplo.com/recursos/ia_lecturas.pdf",
      },
    ],
    estudiantesInscritos: 95,
    calificacionPromedio: 4.5,
  },
]);