//4-Inserción colección Evaluaciones
db.Evaluaciones.insertMany([
  {
    _id: "E001",
    cursoID: "C001",
    titulo: "Quiz: Fundamentos de MongoDB",
    tipo: "Quiz",
    descripcion: "Cuestionario para evaluar la comprensión de los conceptos básicos y la instalación de MongoDB.",
    fechaCreacion: ISODate("2025-05-20T10:00:00-06:00"),
    preguntas: ["Q001", "Q002", "Q003", "Q004", "Q005"],
    criteriosCalificacion: null,
    puntajeMaximo: 20,
  },
  {
    _id: "E002",
    cursoID: "C002",
    titulo: "Tarea: Manipulación del DOM con JavaScript",
    tipo: "Tarea",
    descripcion: "Crea una pequeña aplicación web que manipule elementos del DOM usando JavaScript puro.",
    fechaCreacion: ISODate("2025-05-25T09:30:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "El código debe ser funcional, limpio y seguir las mejores prácticas de JavaScript. Se evaluará la creatividad y la correcta manipulación del DOM.",
    puntajeMaximo: 50,
  },
  {
    _id: "E003",
    cursoID: "C003",
    titulo: "Examen Final: Diseño Gráfico con Photoshop",
    tipo: "Examen Final",
    descripcion: "Proyecto final donde aplicarás todas las herramientas y técnicas aprendidas en el curso de Photoshop.",
    fechaCreacion: ISODate("2025-05-10T14:00:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "Calidad del diseño, uso correcto de capas y máscaras, retoque fotográfico profesional, creatividad y originalidad.",
    puntajeMaximo: 100,
  },
  {
    _id: "E004",
    cursoID: "C004",
    titulo: "Proyecto Final: Aplicación React/Redux",
    tipo: "Tarea",
    descripcion: "Desarrolla una aplicación web completa utilizando React y Redux, integrando al menos una API externa.",
    fechaCreacion: ISODate("2025-06-01T10:00:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "Funcionalidad, escalabilidad, manejo de estado con Redux, diseño de UI/UX, calidad del código y despliegue.",
    puntajeMaximo: 100,
  },
  {
    _id: "E005",
    cursoID: "C005",
    titulo: "Quiz: Librerías Esenciales de Python (NumPy/Pandas)",
    tipo: "Quiz",
    descripcion: "Evaluación sobre el uso de NumPy y Pandas para el análisis y manipulación de datos en Python.",
    fechaCreacion: ISODate("2025-05-15T10:00:00-06:00"),
    preguntas: ["Q006", "Q007", "Q008", "Q009", "Q010"],
    criteriosCalificacion: null,
    puntajeMaximo: 25,
  },
  {
    _id: "E006",
    cursoID: "C006",
    titulo: "Tarea: Propuesta de Estrategia de Contenido",
    tipo: "Tarea",
    descripcion: "Diseña una propuesta de estrategia de contenido para una marca ficticia o real, incluyendo objetivos y KPIs.",
    fechaCreacion: ISODate("2025-05-28T11:00:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "Claridad de la propuesta, viabilidad de las estrategias, definición de métricas, creatividad y presentación.",
    puntajeMaximo: 70,
  },
  {
    _id: "E007",
    cursoID: "C007",
    titulo: "Quiz: Amenazas Comunes en Ciberseguridad",
    tipo: "Quiz",
    descripcion: "Cuestionario para identificar y comprender las principales amenazas y vulnerabilidades de seguridad informática.",
    fechaCreacion: ISODate("2025-05-01T12:00:00-06:00"),
    preguntas: ["Q011", "Q012", "Q013", "Q014", "Q015"],
    criteriosCalificacion: null,
    puntajeMaximo: 20,
  },
  {
    _id: "E008",
    cursoID: "C008",
    titulo: "Tarea: Análisis de Caso de Uso de Blockchain",
    tipo: "Tarea",
    descripcion: "Investiga y presenta un caso de uso innovador de la tecnología blockchain en cualquier industria.",
    fechaCreacion: ISODate("2025-06-05T09:00:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "Profundidad de la investigación, claridad de la explicación, relevancia del caso de uso y presentación.",
    puntajeMaximo: 60,
  },
  {
    _id: "E009",
    cursoID: "C009",
    titulo: "Proyecto Final: Aplicación Móvil con Flutter",
    tipo: "Examen Final",
    descripcion: "Construye una aplicación móvil funcional con Flutter que resuelva un problema real o simule un servicio.",
    fechaCreacion: ISODate("2025-05-30T14:00:00-06:00"),
    preguntas: [],
    criteriosCalificacion: "Funcionalidad de la aplicación, diseño de UI/UX, uso de widgets avanzados, manejo de estado y optimización.",
    puntajeMaximo: 100,
  },
  {
    _id: "E010",
    cursoID: "C010",
    titulo: "Quiz: Conceptos Clave de Inteligencia Artificial",
    tipo: "Quiz",
    descripcion: "Evalúa tu comprensión de los conceptos fundamentales de la Inteligencia Artificial y el Machine Learning.",
    fechaCreacion: ISODate("2025-06-08T11:00:00-06:00"),
    preguntas: ["Q016", "Q017", "Q018", "Q019", "Q020"],
    criteriosCalificacion: null,
    puntajeMaximo: 20,
  },
]);
