//3-Inserción colección Lecciones
db.Lecciones.insertMany([
  {
    _id: "L001",
    cursosID: "C001",
    titulo: "Bienvenida e Introducción a MongoDB",
    descripcion: "Una visión general de qué es MongoDB, sus ventajas y por qué usarlo para tus proyectos.",
    tipo: "video",
    contenido: "https://youtube.com/watch?v=intro_mongodb",
    duracionEstimada: "15 minutos",
    orden: 1,
    recursosAdicionales: [],
  },
  {
    _id: "L002",
    cursosID: "C001",
    titulo: "Instalación y Configuración de MongoDB",
    descripcion: "Pasos detallados para instalar MongoDB en diferentes sistemas operativos y configurarlo para desarrollo.",
    tipo: "texto",
    contenido: "En esta lección aprenderás a instalar MongoDB en Windows, macOS y Linux. Asegúrate de seguir las instrucciones cuidadosamente...",
    duracionEstimada: null,
    orden: 2,
    recursosAdicionales: [
      {
        nombre: "Guía oficial de instalación",
        tipo: "enlace externo",
        url: "https://docs.mongodb.com/manual/installation/",
      },
    ],
  },
  {
    _id: "L003",
    cursosID: "C001",
    titulo: "Quiz: Fundamentos de MongoDB",
    descripcion: "Pon a prueba tus conocimientos sobre los conceptos básicos y la instalación de MongoDB.",
    tipo: "quiz",
    contenido: "Q001",
    duracionEstimada: "10 minutos",
    orden: 3,
    recursosAdicionales: [],
  },
  {
    _id: "L006",
    cursosID: "C002",
    titulo: "Variables y Tipos de Datos en JavaScript",
    descripcion: "Explora los diferentes tipos de variables y datos primitivos en JavaScript moderno (ES6+).",
    tipo: "video",
    contenido: "https://youtube.com/watch?v=js_variables",
    duracionEstimada: "20 minutos",
    orden: 1,
    recursosAdicionales: [],
  },
  {
    _id: "L007",
    cursosID: "C002",
    titulo: "Control de Flujo: Condicionales y Bucles",
    descripcion: "Aprende a controlar el flujo de tu programa con sentencias `if/else`, `switch` y bucles (`for`, `while`).",
    tipo: "texto",
    contenido: "El control de flujo es esencial en programación. Veremos cómo tomar decisiones y repetir acciones...",
    duracionEstimada: null,
    orden: 2,
    recursosAdicionales: [
      {
        nombre: "Ejercicios de control de flujo",
        tipo: "archivo",
        url: "https://ejemplo.com/recursos/js_flujo_ejercicios.zip",
      },
    ],
  },
  {
    _id: "L012",
    cursosID: "C003",
    titulo: "Interfaz y Herramientas Básicas de Photoshop",
    descripcion: "Familiarízate con el espacio de trabajo de Photoshop y las herramientas fundamentales para empezar a diseñar.",
    tipo: "video",
    contenido: "https://youtube.com/watch?v=photoshop_interface",
    duracionEstimada: "18 minutos",
    orden: 1,
    recursosAdicionales: [],
  },
  {
    _id: "L016",
    cursosID: "C004",
    titulo: "Introducción a React: Componentes y JSX",
    descripcion: "Entiende la filosofía de React, cómo funcionan los componentes y la sintaxis JSX para crear UI.",
    tipo: "video",
    contenido: "https://youtube.com/watch?v=react_intro",
    duracionEstimada: "25 minutos",
    orden: 1,
    recursosAdicionales: [],
  },
  {
    _id: "L023",
    cursosID: "C005",
    titulo: "Primeros Pasos en Python y Tipos de Datos",
    descripcion: "Configura tu entorno de Python y aprende sobre variables, números, cadenas y listas.",
    tipo: "texto",
    contenido: "Python es un lenguaje versátil. Empezaremos con lo básico para que te familiarices con la sintaxis...",
    duracionEstimada: null,
    orden: 1,
    recursosAdicionales: [
      {
        nombre: "Recursos de instalación de Python",
        tipo: "enlace externo",
        url: "https://www.python.org/downloads/",
      },
    ],
  },
  {
    _id: "L028",
    cursosID: "C006",
    titulo: "Planificación de Contenido Estratégico",
    descripcion: "Define tu público objetivo y cómo crear un plan de contenido que resuene con él.",
    tipo: "video",
    contenido: "https://youtube.com/watch?v=contenido_estrategia",
    duracionEstimada: "22 minutos",
    orden: 1,
    recursosAdicionales: [],
  },
  {
    _id: "L032",
    cursosID: "C007",
    titulo: "Principios Fundamentales de la Ciberseguridad",
    descripcion: "Conoce los conceptos clave como confidencialidad, integridad y disponibilidad en seguridad informática.",
    tipo: "texto",
    contenido: "La ciberseguridad es un campo en constante evolución. Comprender sus principios es el primer paso...",
    duracionEstimada: null,
    orden: 1,
    recursosAdicionales: [
      {
        nombre: "Lectura: Los pilares de la seguridad",
        tipo: "PDF",
        url: "https://ejemplo.com/recursos/pilares_seguridad.pdf",
      },
    ],
  },
]);