//Script BD (Inserciones de datos asi como los comandos de creación)
//Creación de la base de datos

//use Conecta_Futuro_MongoDB

//Creación de colecciones
//1-Colección Usuarios
db.createCollection("Usuarios");
//2-Colección Suscripciones
db.createCollection("Suscripciones");
//3-Colección Suscripción
db.createCollection("Suscripción");
//4-Colección Preguntas
db.createCollection("Preguntas");
//5-Colección Lecciones
db.createCollection("Lecciones");
//6-Colección Inscripciones
db.createCollection("Inscripciones");
//7-Colección Evaluaciones
db.createCollection("Evaluaciones");
//8-Colección Cursos
db.createCollection("Cursos");
//9-Colección Comentarios
db.createCollection("Comentarios");
//10-Colección Certificados
db.createCollection("Certificados");

//Inserción de datos (100 registros en la BD).

//1-Inserción colección Usuarios 
db.Usuarios.insertMany([
  {
    _id: "U0001",
    nombre: "Ana",
    apellido: "García",
    email: "ana.garcia@conectafuturo.com",
    contrasena: "$2b$10$abcdefghijklmnopqrstuvwxyza.hash_conecta_futuro_2025_1",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "ana_garcia.jpg",
      correo: "ana.garcia@conectafuturo.com",
      pais: "México",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:20-06:00",
        ultimoAcceso: "2025-06-10T16:15:00-06:00",
      },
    },
    cusosInscritos: "C001",
    cursosCompletados: {
      progreso: 0.75,
      leccionActual: "Introducción a MongoDB",
      porcentajeCompletado: 75.5,
    },
    certificadosObtenidos: "CERT001",
    historialActividad: ["Acceso a curso", "Envío de tarea"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "I0001",
    nombre: "Juan",
    apellido: "Martínez",
    email: "juan.martinez@conectafuturo.com",
    contrasena: "$2b$10$bcdefghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_2",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "juan_martinez.png",
      correo: "juan.martinez@conectafuturo.com",
      pais: "España",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:25-06:00",
        ultimoAcceso: "2025-06-10T16:18:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Todos los cursos creados",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Creación de curso", "Revisión de tareas"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0002",
    nombre: "María",
    apellido: "López",
    email: "maria.lopez@conectafuturo.com",
    contrasena: "$2b$10$cdefghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_3",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "inactivo",
    informacionPerfil: {
      fotoPerfil: "maria_lopez.jpg",
      correo: "maria.lopez@conectafuturo.com",
      pais: "Argentina",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:30-06:00",
        ultimoAcceso: "2025-06-10T16:09:00-06:00",
      },
    },
    cusosInscritos: "C002",
    cursosCompletados: {
      progreso: 0.20,
      leccionActual: "Fundamentos de JavaScript",
      porcentajeCompletado: 20.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Inscripción a curso"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "A0001",
    nombre: "Carlos",
    apellido: "Rodríguez",
    email: "carlos.rodriguez@conectafuturo.com",
    contrasena: "$2b$10$defghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_4",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "administrador",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "carlos_rodriguez.png",
      correo: "carlos.rodriguez@conectafuturo.com",
      pais: "Colombia",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:35-06:00",
        ultimoAcceso: "2025-06-10T16:20:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: null,
    certificadosObtenidos: null,
    historialActividad: ["Gestión de usuarios", "Creación de cursos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0003",
    nombre: "Laura",
    apellido: "Fernández",
    email: "laura.fernandez@conectafuturo.com",
    contrasena: "$2b$10$efghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_5",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "pendiente",
    informacionPerfil: {
      fotoPerfil: "laura_fernandez.jpg",
      correo: "laura.fernandez@conectafuturo.com",
      pais: "Chile",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:40-06:00",
        ultimoAcceso: "2025-06-10T16:09:30-06:00",
      },
    },
    cusosInscritos: "C003",
    cursosCompletados: {
      progreso: 0.0,
      leccionActual: "Pendiente de inicio",
      porcentajeCompletado: 0.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Registro de cuenta"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0004",
    nombre: "Pedro",
    apellido: "Gómez",
    email: "pedro.gomez@conectafuturo.com",
    contrasena: "$2b$10$fghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_6",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "pedro_gomez.jpg",
      correo: "pedro.gomez@conectafuturo.com",
      pais: "Perú",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:45-06:00",
        ultimoAcceso: "2025-06-10T16:22:00-06:00",
      },
    },
    cusosInscritos: "C004",
    cursosCompletados: {
      progreso: 0.90,
      leccionActual: "Desarrollo Web con React",
      porcentajeCompletado: 90.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Avance en curso", "Foro de discusión"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "I0002",
    nombre: "Sofía",
    apellido: "Díaz",
    email: "sofia.diaz@conectafuturo.com",
    contrasena: "$2b$10$ghijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_7",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "sofia_diaz.png",
      correo: "sofia.diaz@conectafuturo.com",
      pais: "Uruguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:50-06:00",
        ultimoAcceso: "2025-06-10T16:25:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Curso de Diseño Gráfico",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Publicación de contenido", "Interacción con alumnos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0005",
    nombre: "Diego",
    apellido: "Ruiz",
    email: "diego.ruiz@conectafuturo.com",
    contrasena: "$2b$10$hijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_8",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "diego_ruiz.jpg",
      correo: "diego.ruiz@conectafuturo.com",
      pais: "Ecuador",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:08:55-06:00",
        ultimoAcceso: "2025-06-10T16:28:00-06:00",
      },
    },
    cusosInscritos: "C005",
    cursosCompletados: {
      progreso: 0.50,
      leccionActual: "Programación en Python",
      porcentajeCompletado: 50.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Cuestionario completado"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0006",
    nombre: "Elena",
    apellido: "Sánchez",
    email: "elena.sanchez@conectafuturo.com",
    contrasena: "$2b$10$ijklmnopqrstuvwxyzz.hash_conecta_futuro_2025_9",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "elena_sanchez.jpg",
      correo: "elena.sanchez@conectafuturo.com",
      pais: "Venezuela",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:00-06:00",
        ultimoAcceso: "2025-06-10T16:30:00-06:00",
      },
    },
    cusosInscritos: "C006",
    cursosCompletados: {
      progreso: 0.85,
      leccionActual: "Marketing Digital",
      porcentajeCompletado: 85.0,
    },
    certificadosObtenidos: "CERT002",
    historialActividad: ["Descarga de material", "Comentario en lección"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0007",
    nombre: "Pablo",
    apellido: "Torres",
    email: "pablo.torres@conectafuturo.com",
    contrasena: "$2b$10$klmnopqrstuvwxyzz.hash_conecta_futuro_2025_10",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "pendiente",
    informacionPerfil: {
      fotoPerfil: "pablo_torres.jpg",
      correo: "pablo.torres@conectafuturo.com",
      pais: "Paraguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:05-06:00",
        ultimoAcceso: "2025-06-10T16:09:10-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 0.0,
      leccionActual: "Aún no ha iniciado",
      porcentajeCompletado: 0.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Creación de cuenta"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "U0008",
    nombre: "Isabella",
    apellido: "Castro",
    email: "isabella.castro@conectafuturo.com",
    contrasena: "$2b$10$mnopqrstuvwxyzz.hash_conecta_futuro_2025_11",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "isabella_castro.jpg",
      correo: "isabella.castro@conectafuturo.com",
      pais: "México",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:10-06:00",
        ultimoAcceso: "2025-06-10T16:32:00-06:00",
      },
    },
    cusosInscritos: "C007",
    cursosCompletados: {
      progreso: 0.60,
      leccionActual: "Inteligencia Artificial",
      porcentajeCompletado: 60.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Participación en foro", "Envío de proyecto"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0009",
    nombre: "Miguel",
    apellido: "Herrera",
    email: "miguel.herrera@conectafuturo.com",
    contrasena: "$2b$10$nopqrstuvwxyzz.hash_conecta_futuro_2025_12",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "miguel_herrera.jpg",
      correo: "miguel.herrera@conectafuturo.com",
      pais: "España",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:15-06:00",
        ultimoAcceso: "2025-06-10T16:35:00-06:00",
      },
    },
    cusosInscritos: "C008",
    cursosCompletados: {
      progreso: 0.95,
      leccionActual: "Cloud Computing",
      porcentajeCompletado: 95.0,
    },
    certificadosObtenidos: "CERT003",
    historialActividad: ["Evaluación de curso", "Descarga de recursos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0010",
    nombre: "Valentina",
    apellido: "Mendoza",
    email: "valentina.mendoza@conectafuturo.com",
    contrasena: "$2b$10$pqrstuvwxyzz.hash_conecta_futuro_2025_13",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "inactivo",
    informacionPerfil: {
      fotoPerfil: "valentina_mendoza.jpg",
      correo: "valentina.mendoza@conectafuturo.com",
      pais: "Argentina",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:20-06:00",
        ultimoAcceso: "2025-06-10T16:10:00-06:00",
      },
    },
    cusosInscritos: "C009",
    cursosCompletados: {
      progreso: 0.10,
      leccionActual: "Big Data",
      porcentajeCompletado: 10.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Inscripción a curso"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "I0003",
    nombre: "Alejandra",
    apellido: "Vargas",
    email: "alejandra.vargas@conectafuturo.com",
    contrasena: "$2b$10$qrstuvwxyzz.hash_conecta_futuro_2025_14",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "alejandra_vargas.png",
      correo: "alejandra.vargas@conectafuturo.com",
      pais: "Colombia",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:25-06:00",
        ultimoAcceso: "2025-06-10T16:38:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Desarrollo de Apps Móviles",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Creación de módulos", "Respuesta a preguntas"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0011",
    nombre: "Ricardo",
    apellido: "Salazar",
    email: "ricardo.salazar@conectafuturo.com",
    contrasena: "$2b$10$rstuvwxyzz.hash_conecta_futuro_2025_15",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "ricardo_salazar.jpg",
      correo: "ricardo.salazar@conectafuturo.com",
      pais: "Chile",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:30-06:00",
        ultimoAcceso: "2025-06-10T16:40:00-06:00",
      },
    },
    cusosInscritos: "C010",
    cursosCompletados: {
      progreso: 0.80,
      leccionActual: "Ciberseguridad Fundamentos",
      porcentajeCompletado: 80.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Examen completado", "Material de estudio"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0012",
    nombre: "Daniela",
    apellido: "Rojas",
    email: "daniela.rojas@conectafuturo.com",
    contrasena: "$2b$10$tuvwxyzz.hash_conecta_futuro_2025_16",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "daniela_rojas.jpg",
      correo: "daniela.rojas@conectafuturo.com",
      pais: "Perú",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:35-06:00",
        ultimoAcceso: "2025-06-10T16:42:00-06:00",
      },
    },
    cusosInscritos: "C011",
    cursosCompletados: {
      progreso: 0.70,
      leccionActual: "Blockchain Esencial",
      porcentajeCompletado: 70.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Video visto", "Práctica realizada"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "I0004", // Se corrigió el ID que estaba duplicado (anteriormente I0003)
    nombre: "Andrés",
    apellido: "Silva",
    email: "andres.silva@conectafuturo.com",
    contrasena: "$2b$10$uvwxyzz.hash_conecta_futuro_2025_17",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "andres_silva.png",
      correo: "andres.silva@conectafuturo.com",
      pais: "Uruguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:40-06:00",
        ultimoAcceso: "2025-06-10T16:45:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Fundamentos de Data Science",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Actualización de curso", "Soporte a estudiantes"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0013",
    nombre: "Paula",
    apellido: "Ortiz",
    email: "paula.ortiz@conectafuturo.com",
    contrasena: "$2b$10$vwxyzz.hash_conecta_futuro_2025_18",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "paula_ortiz.jpg",
      correo: "paula.ortiz@conectafuturo.com",
      pais: "Ecuador",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:45-06:00",
        ultimoAcceso: "2025-06-10T16:48:00-06:00",
      },
    },
    cusosInscritos: "C012",
    cursosCompletados: {
      progreso: 0.45,
      leccionActual: "Programación Orientada a Objetos",
      porcentajeCompletado: 45.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Consulta a instructor", "Ejercicios resueltos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0014",
    nombre: "Gabriel",
    apellido: "Núñez",
    email: "gabriel.nunez@conectafuturo.com",
    contrasena: "$2b$10$wxyzz.hash_conecta_futuro_2025_19",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "gabriel_nunez.jpg",
      correo: "gabriel.nunez@conectafuturo.com",
      pais: "Venezuela",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:50-06:00",
        ultimoAcceso: "2025-06-10T16:50:00-06:00",
      },
    },
    cusosInscritos: "C013",
    cursosCompletados: {
      progreso: 0.88,
      leccionActual: "Gestión de Proyectos IT",
      porcentajeCompletado: 88.0,
    },
    certificadosObtenidos: "CERT004",
    historialActividad: ["Proyecto finalizado", "Sesión en vivo"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0015",
    nombre: "Camila",
    apellido: "Castro",
    email: "camila.castro@conectafuturo.com",
    contrasena: "$2b$10$xyzz.hash_conecta_futuro_2025_20",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "pendiente",
    informacionPerfil: {
      fotoPerfil: "camila_castro.jpg",
      correo: "camila.castro@conectafuturo.com",
      pais: "Paraguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:09:55-06:00",
        ultimoAcceso: "2025-06-10T16:10:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 0.0,
      leccionActual: "Aún no ha iniciado",
      porcentajeCompletado: 0.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Creación de cuenta"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "U0016",
    nombre: "Lucas",
    apellido: "Giménez",
    email: "lucas.gimenez@conectafuturo.com",
    contrasena: "$2b$10$yz.hash_conecta_futuro_2025_21",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "lucas_gimenez.jpg",
      correo: "lucas.gimenez@conectafuturo.com",
      pais: "México",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:00-06:00",
        ultimoAcceso: "2025-06-10T16:55:00-06:00",
      },
    },
    cusosInscritos: "C014",
    cursosCompletados: {
      progreso: 0.70,
      leccionActual: "Desarrollo Frontend",
      porcentajeCompletado: 70.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Proyecto individual", "Revisión de código"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0017",
    nombre: "Sofía",
    apellido: "Ramírez",
    email: "sofia.ramirez@conectafuturo.com",
    contrasena: "$2b$10$z.hash_conecta_futuro_2025_22",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "sofia_ramirez.jpg",
      correo: "sofia.ramirez@conectafuturo.com",
      pais: "España",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:05-06:00",
        ultimoAcceso: "2025-06-10T16:58:00-06:00",
      },
    },
    cusosInscritos: "C015",
    cursosCompletados: {
      progreso: 0.92,
      leccionActual: "Desarrollo Backend",
      porcentajeCompletado: 92.0,
    },
    certificadosObtenidos: "CERT005",
    historialActividad: ["Finalización de módulo", "Entrega de proyecto"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "I0005", // Se corrigió el ID que estaba duplicado (anteriormente I0004)
    nombre: "Martín",
    apellido: "Flores",
    email: "martin.flores@conectafuturo.com",
    contrasena: "$2b$10$aa.hash_conecta_futuro_2025_23",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "martin_flores.png",
      correo: "martin.flores@conectafuturo.com",
      pais: "Argentina",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:10-06:00",
        ultimoAcceso: "2025-06-10T17:00:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Bases de Datos SQL y NoSQL",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Creación de ejercicios", "Respuesta a dudas"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0018",
    nombre: "Mariana",
    apellido: "Cruz",
    email: "mariana.cruz@conectafuturo.com",
    contrasena: "$2b$10$ab.hash_conecta_futuro_2025_24",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "mariana_cruz.jpg",
      correo: "mariana.cruz@conectafuturo.com",
      pais: "Colombia",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:15-06:00",
        ultimoAcceso: "2025-06-10T17:02:00-06:00",
      },
    },
    cusosInscritos: "C016",
    cursosCompletados: {
      progreso: 0.30,
      leccionActual: "Diseño UX/UI",
      porcentajeCompletado: 30.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Inicio de módulo", "Lectura de material"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0019",
    nombre: "Javier",
    apellido: "Pérez",
    email: "javier.perez@conectafuturo.com",
    contrasena: "$2b$10$ac.hash_conecta_futuro_2025_25",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "javier_perez.jpg",
      correo: "javier.perez@conectafuturo.com",
      pais: "Chile",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:20-06:00",
        ultimoAcceso: "2025-06-10T17:05:00-06:00",
      },
    },
    cusosInscritos: "C017",
    cursosCompletados: {
      progreso: 0.82,
      leccionActual: "Desarrollo de Videojuegos",
      porcentajeCompletado: 82.0,
    },
    certificadosObtenidos: "CERT006",
    historialActividad: ["Proyecto completado", "Compartir en redes"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0020",
    nombre: "Valeria",
    apellido: "Contreras",
    email: "valeria.contreras@conectafuturo.com",
    contrasena: "$2b$10$ad.hash_conecta_futuro_2025_26",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "pendiente",
    informacionPerfil: {
      fotoPerfil: "valeria_contreras.jpg",
      correo: "valeria.contreras@conectafuturo.com",
      pais: "Perú",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:25-06:00",
        ultimoAcceso: "2025-06-10T16:10:30-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 0.0,
      leccionActual: "Aún no ha iniciado",
      porcentajeCompletado: 0.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Registro de cuenta"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "U0021",
    nombre: "Fernando",
    apellido: "Morales",
    email: "fernando.morales@conectafuturo.com",
    contrasena: "$2b$10$ae.hash_conecta_futuro_2025_27",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "fernando_morales.jpg",
      correo: "fernando.morales@conectafuturo.com",
      pais: "Uruguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:30-06:00",
        ultimoAcceso: "2025-06-10T17:08:00-06:00",
      },
    },
    cusosInscritos: "C018",
    cursosCompletados: {
      progreso: 0.65,
      leccionActual: "Redes y Servidores",
      porcentajeCompletado: 65.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Participación en webinar", "Descarga de laboratorios"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0022",
    nombre: "Adriana",
    apellido: "Benítez",
    email: "adriana.benitez@conectafuturo.com",
    contrasena: "$2b$10$af.hash_conecta_futuro_2025_28",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "adriana_benitez.jpg",
      correo: "adriana.benitez@conectafuturo.com",
      pais: "Ecuador",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:35-06:00",
        ultimoAcceso: "2025-06-10T17:10:00-06:00",
      },
    },
    cusosInscritos: "C019",
    cursosCompletados: {
      progreso: 0.98,
      leccionActual: "Programación en C#",
      porcentajeCompletado: 98.0,
    },
    certificadosObtenidos: "CERT007",
    historialActividad: ["Proyecto finalizado", "Revisión de errores"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0023",
    nombre: "Jorge",
    apellido: "Romero",
    email: "jorge.romero@conectafuturo.com",
    contrasena: "$2b$10$ag.hash_conecta_futuro_2025_29",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "jorge_romero.jpg",
      correo: "jorge.romero@conectafuturo.com",
      pais: "Venezuela",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:40-06:00",
        ultimoAcceso: "2025-06-10T17:12:00-06:00",
      },
    },
    cusosInscritos: "C020",
    cursosCompletados: {
      progreso: 0.70,
      leccionActual: "Machine Learning Avanzado",
      porcentajeCompletado: 70.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Entrega de tarea", "Sesión de preguntas y respuestas"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0024",
    nombre: "Jimena",
    apellido: "Miranda",
    email: "jimena.miranda@conectafuturo.com",
    contrasena: "$2b$10$ah.hash_conecta_futuro_2025_30",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "pendiente",
    informacionPerfil: {
      fotoPerfil: "jimena_miranda.jpg",
      correo: "jimena.miranda@conectafuturo.com",
      pais: "Paraguay",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:45-06:00",
        ultimoAcceso: "2025-06-10T16:10:50-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 0.0,
      leccionActual: "Aún no ha iniciado",
      porcentajeCompletado: 0.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Registro de cuenta"],
    preferencias: {
      notificaciones: false,
      idioma: "es",
    },
  },
  {
    _id: "U0025",
    nombre: "Gonzalo",
    apellido: "Díaz",
    email: "gonzalo.diaz@conectafuturo.com",
    contrasena: "$2b$10$ai.hash_conecta_futuro_2025_31",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "gonzalo_diaz.jpg",
      correo: "gonzalo.diaz@conectafuturo.com",
      pais: "México",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:50-06:00",
        ultimoAcceso: "2025-06-10T17:15:00-06:00",
      },
    },
    cusosInscritos: "C021",
    cursosCompletados: {
      progreso: 0.80,
      leccionActual: "Análisis de Datos con R",
      porcentajeCompletado: 80.0,
    },
    certificadosObtenidos: "CERT008",
    historialActividad: ["Examen final", "Revisión de conceptos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0026",
    nombre: "Lorena",
    apellido: "Serrano",
    email: "lorena.serrano@conectafuturo.com",
    contrasena: "$2b$10$aj.hash_conecta_futuro_2025_32",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "lorena_serrano.jpg",
      correo: "lorena.serrano@conectafuturo.com",
      pais: "España",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:10:55-06:00",
        ultimoAcceso: "2025-06-10T17:18:00-06:00",
      },
    },
    cusosInscritos: "C022",
    cursosCompletados: {
      progreso: 0.55,
      leccionActual: "Programación Funcional",
      porcentajeCompletado: 55.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Práctica de código", "Lectura complementaria"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "I0005",
    nombre: "Roberto",
    apellido: "Castro",
    email: "roberto.castro@conectafuturo.com",
    contrasena: "$2b$10$ak.hash_conecta_futuro_2025_33",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "instructor",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "roberto_castro.png",
      correo: "roberto.castro@conectafuturo.com",
      pais: "Argentina",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:11:00-06:00",
        ultimoAcceso: "2025-06-10T17:20:00-06:00",
      },
    },
    cusosInscritos: null,
    cursosCompletados: {
      progreso: 1.0,
      leccionActual: "Arquitectura de Software",
      porcentajeCompletado: 100.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Diseño de currículo", "Mentoría a estudiantes"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0027",
    nombre: "Sofía",
    apellido: "Vega",
    email: "sofia.vega@conectafuturo.com",
    contrasena: "$2b$10$al.hash_conecta_futuro_2025_34",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "sofia_vega.jpg",
      correo: "sofia.vega@conectafuturo.com",
      pais: "Colombia",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:11:05-06:00",
        ultimoAcceso: "2025-06-10T17:22:00-06:00",
      },
    },
    cusosInscritos: "C023",
    cursosCompletados: {
      progreso: 0.40,
      leccionActual: "Programación en Kotlin",
      porcentajeCompletado: 40.0,
    },
    certificadosObtenidos: null,
    historialActividad: ["Inicio de curso", "Primeros videos"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  },
  {
    _id: "U0028",
    nombre: "Esteban",
    apellido: "Molina",
    email: "esteban.molina@conectafuturo.com",
    contrasena: "$2b$10$am.hash_conecta_futuro_2025_35",
    fechaRegistro: ISODate("2025-06-10T16:08:15-06:00"),
    rol: "Estudiante",
    estado: "activo",
    informacionPerfil: {
      fotoPerfil: "esteban_molina.jpg",
      correo: "esteban.molina@conectafuturo.com",
      pais: "Chile",
      actividadPerfil: {
        primerAcceso: "2025-06-10T16:11:10-06:00",
        ultimoAcceso: "2025-06-10T17:25:00-06:00",
      },
    },
    cusosInscritos: "C024",
    cursosCompletados: {
      progreso: 0.90,
      leccionActual: "Desarrollo con Ruby on Rails",
      porcentajeCompletado: 90.0,
    },
    certificadosObtenidos: "CERT009",
    historialActividad: ["Deployment de proyecto", "Debugging"],
    preferencias: {
      notificaciones: true,
      idioma: "es",
    },
  }
])